; r1 = square size, r2 = # of total items to read, r3 = current number,
; r4 = # of items read thus far, r6 = inputLoop, r10 = memory counter
.code
	clr r1
	in r1, r0
	clr r4
	mul r2, r1, r1
	add r2, r2, r2
	ld r6, :inputLoop 
	ld r10, 65536 
	ld r22, 8
:inputLoop
	in r3, r0
	mov (r10)(0), r3
	addi r10, 8
	addi r4, 1
	brgt r6, r2, r4
; r7 = row counter, r8 = col counter, r9 = dot product counter, r11 = rowLoop, 
; r12 = colLoop, r13 = dotProdLoop, r14 = currentMatrixOneAddy, r15 = currentMatrixTwoAddy,
; r16 = actualMatrixOne, r17 = actualMatrixTwo
; r20 = tempMatrixOne, r21 = tempMatrixTwo, r22 = 8, r23 = tmep product for dot product
; r24 = running dot product sum, r25 = 3 (output)
	clr r7
	clr r8
	clr r9 
	ld r25, 1 
	ld r11, :rowLoop 
	ld r12, :colLoop
	ld r13, :dotProdLoop
:rowLoop

:colLoop 
	clr r9 
	clr r24 
:dotProdLoop 
	clr r14 
	clr r15
	ld r14, 65536
	ld r15, 65536
; get A value 
	mul r20, r7, r1
	add r20, r20, r9
	mul r20, r20, r22
	add r14, r14, r20 
	mov r16, (r14)(0)
; get B value
	clr r20
	mul r20, r1, r1
	mul r20, r20, r22
	add r15, r15, r20
	clr r20 
	clr r21
	mul r20, r1, r9
	add r20, r20, r8
	mul r20, r20, r22
	add r15, r15, r20
	mov r17, (r15)(0)
; multiply values 
	mulf r23, r16, r17
; add to running sum
	addf r24, r24, r23 
	addi r9, 1
	brgt r13, r1, r9
; dot product done 
	out r25, r24
	addi r8, 1
	brgt r12, r1, r8
; col done 
	clr r8
	addi r7, 1
	brgt r11, r1, r7
; row done 
	halt