.code
	xor r10, r10, r10
	xor r10, r10, r10
	addi r10, 0
	shftli r10, 12
	addi r10, 0
	shftli r10, 12
	addi r10, 0
	shftli r10, 12
	addi r10, 1
	shftli r10, 12
	addi r10, 0
	shftli r10, 4
	addi r10, 0
	xor r1, r1, r1
	priv r1, r0, r0, 3
	xor r2, r2, r2
	xor r5, r5, r5
	addi r5, 0
	shftli r5, 12
	addi r5, 0
	shftli r5, 12
	addi r5, 0
	shftli r5, 12
	addi r5, 0
	shftli r5, 12
	addi r5, 533
	shftli r5, 4
	addi r5, 12
	xor r6, r6, r6
	addi r6, 0
	shftli r6, 12
	addi r6, 0
	shftli r6, 12
	addi r6, 0
	shftli r6, 12
	addi r6, 0
	shftli r6, 12
	addi r6, 522
	shftli r6, 4
	addi r6, 4
	brgt r5, r2, r1
	priv r3, r0, r0, 3
	mov (r10)(0), r3
	addi r10, 8
	addi r2, 1
	brgt r6, r1, r2
	xor r30, r30, r30
	addi r30, 0
	shftli r30, 12
	addi r30, 0
	shftli r30, 12
	addi r30, 0
	shftli r30, 12
	addi r30, 1
	shftli r30, 12
	addi r30, 0
	shftli r30, 4
	addi r30, 0
	xor r7, r7, r7
	addi r7, 0
	shftli r7, 12
	addi r7, 0
	shftli r7, 12
	addi r7, 0
	shftli r7, 12
	addi r7, 0
	shftli r7, 12
	addi r7, 544
	shftli r7, 4
	addi r7, 8
	xor r20, r20, r20
	xor r21, r21, r21
	mov r21, r1
	subi r21, 1
	xor r12, r12, r12
	addi r12, 0
	shftli r12, 12
	addi r12, 0
	shftli r12, 12
	addi r12, 0
	shftli r12, 12
	addi r12, 0
	shftli r12, 12
	addi r12, 545
	shftli r12, 4
	addi r12, 4
	priv r15, r0, r0, 3
	brgt r12, r20, r21 
	add r22, r20, r21 
	shftri r22, 1 
	mov r23, r22
	shftli r23, 3 
	add r19, r30, r23 
	mov r18, (r19)(0) 
	xor r25, r18, r15
	xor r26, r26, r26
	addi r26, 0
	shftli r26, 12
	addi r26, 0
	shftli r26, 12
	addi r26, 0
	shftli r26, 12
	addi r26, 0
	shftli r26, 12
	addi r26, 543
	shftli r26, 4
	addi r26, 8
	brnz r26, r25 
	xor r27, r27, r27
	addi r27, 3 
	xor r28, r28, r28
	addi r28, 102    
	priv r27, r28, r0, 4
	xor r28, r28, r28
	addi r28, 111    
	priv r27, r28, r0, 4
	xor r28, r28, r28
	addi r28, 117    
	priv r27, r28, r0, 4
	xor r28, r28, r28
	addi r28, 110    
	priv r27, r28, r0, 4
	xor r28, r28, r28
	addi r28, 100    
	priv r27, r28, r0, 4
	priv r0, r0, r0, 0
	brgt r7, r18, r15
	mov r20, r22
	addi r20, 1
	br r5 
	mov r21, r22
	subi r21, 1
	br r5 
	xor r27, r27, r27
	addi r27, 3
	xor r28, r28, r28
	addi r28, 110    
	priv r27, r28, r0, 4
	xor r28, r28, r28
	addi r28, 111    
	priv r27, r28, r0, 4
	xor r28, r28, r28
	addi r28, 116    
	priv r27, r28, r0, 4
	xor r28, r28, r28
	addi r28, 32     
	priv r27, r28, r0, 4
	xor r28, r28, r28
	addi r28, 102    
	priv r27, r28, r0, 4
	xor r28, r28, r28
	addi r28, 111    
	priv r27, r28, r0, 4
	xor r28, r28, r28
	addi r28, 117    
	priv r27, r28, r0, 4
	xor r28, r28, r28
	addi r28, 110    
	priv r27, r28, r0, 4
	xor r28, r28, r28
	addi r28, 100    
	priv r27, r28, r0, 4
	priv r0, r0, r0, 0
