.code
	xor r1, r1, r1
	priv r1, r0, r0, 3
	xor r4, r4, r4
	mul r2, r1, r1
	add r2, r2, r2
	xor r6, r6, r6
	addi r6, 0
	shftli r6, 12
	addi r6, 0
	shftli r6, 12
	addi r6, 0
	shftli r6, 12
	addi r6, 0
	shftli r6, 12
	addi r6, 522
	shftli r6, 4
	addi r6, 4
	xor r10, r10, r10
	addi r10, 0
	shftli r10, 12
	addi r10, 0
	shftli r10, 12
	addi r10, 0
	shftli r10, 12
	addi r10, 1
	shftli r10, 12
	addi r10, 0
	shftli r10, 4
	addi r10, 0
	xor r22, r22, r22
	addi r22, 0
	shftli r22, 12
	addi r22, 0
	shftli r22, 12
	addi r22, 0
	shftli r22, 12
	addi r22, 0
	shftli r22, 12
	addi r22, 0
	shftli r22, 4
	addi r22, 8
	priv r3, r0, r0, 3
	mov (r10)(0), r3
	addi r10, 8
	addi r4, 1
	brgt r6, r2, r4
	xor r7, r7, r7
	xor r8, r8, r8
	xor r9, r9, r9
	xor r25, r25, r25
	addi r25, 0
	shftli r25, 12
	addi r25, 0
	shftli r25, 12
	addi r25, 0
	shftli r25, 12
	addi r25, 0
	shftli r25, 12
	addi r25, 0
	shftli r25, 4
	addi r25, 1
	xor r11, r11, r11
	addi r11, 0
	shftli r11, 12
	addi r11, 0
	shftli r11, 12
	addi r11, 0
	shftli r11, 12
	addi r11, 0
	shftli r11, 12
	addi r11, 536
	shftli r11, 4
	addi r11, 4
	xor r12, r12, r12
	addi r12, 0
	shftli r12, 12
	addi r12, 0
	shftli r12, 12
	addi r12, 0
	shftli r12, 12
	addi r12, 0
	shftli r12, 12
	addi r12, 536
	shftli r12, 4
	addi r12, 4
	xor r13, r13, r13
	addi r13, 0
	shftli r13, 12
	addi r13, 0
	shftli r13, 12
	addi r13, 0
	shftli r13, 12
	addi r13, 0
	shftli r13, 12
	addi r13, 536
	shftli r13, 4
	addi r13, 12
	xor r9, r9, r9
	xor r24, r24, r24
	xor r14, r14, r14
	xor r15, r15, r15
	xor r14, r14, r14
	addi r14, 0
	shftli r14, 12
	addi r14, 0
	shftli r14, 12
	addi r14, 0
	shftli r14, 12
	addi r14, 1
	shftli r14, 12
	addi r14, 0
	shftli r14, 4
	addi r14, 0
	xor r15, r15, r15
	addi r15, 0
	shftli r15, 12
	addi r15, 0
	shftli r15, 12
	addi r15, 0
	shftli r15, 12
	addi r15, 1
	shftli r15, 12
	addi r15, 0
	shftli r15, 4
	addi r15, 0
	mul r20, r7, r1
	add r20, r20, r9
	mul r20, r20, r22
	add r14, r14, r20 
	mov r16, (r14)(0)
	xor r20, r20, r20
	mul r20, r1, r1
	mul r20, r20, r22
	add r15, r15, r20
	xor r20, r20, r20
	xor r21, r21, r21
	mul r20, r1, r9
	add r20, r20, r8
	mul r20, r20, r22
	add r15, r15, r20
	mov r17, (r15)(0)
	mulf r23, r16, r17
	addf r24, r24, r23 
	addi r9, 1
	brgt r13, r1, r9
	priv r25, r24, r0, 4
	addi r8, 1
	brgt r12, r1, r8
	xor r8, r8, r8
	addi r7, 1
	brgt r11, r1, r7
	priv r0, r0, r0, 0
