.code
	xor r0, r0, r0
	xor r5, r5, r5
	xor r10, r10, r10
	addi r10, 0
	shftli r10, 12
	addi r10, 0
	shftli r10, 12
	addi r10, 0
	shftli r10, 12
	addi r10, 0
	shftli r10, 12
	addi r10, 771
	shftli r10, 4
	addi r10, 9
	xor r15, r15, r15
	addi r15, 0
	shftli r15, 12
	addi r15, 0
	shftli r15, 12
	addi r15, 0
	shftli r15, 12
	addi r15, 0
	shftli r15, 12
	addi r15, 265
	shftli r15, 4
	addi r15, 8
	priv r1, r0, r0, 3
	priv r1, r2, r0, 4
	mov (r31)(-8), r3
	subi r31, 8
	mov (r31)(-8), r20
	subi r31, 8
	mov r4, (r31)(0)
	addi r31, 8
	mov r25, (r31)(0)
	addi r31, 8
	br r15
	priv r0, r0, r0, 0
.data
	42
	100
	255
.code
	add r1, r2, r3
	priv r0, r0, r0, 0
