.data
.code
	add r1, r2, r3
	xor r1, r1, r1
	addi r1, 0
	shftli r1, 12
	addi r1, 0
	shftli r1, 12
	addi r1, 0
	shftli r1, 12
	addi r1, 0
	shftli r1, 12
	addi r1, 0
	shftli r1, 4
	addi r1, 15
.data
.code
.data
	12
	9
.code
	addi r23, 23
	mul r1, r2, r3
	add r1, r2, r3
	xor r1, r1, r1
	addi r1, 0
	shftli r1, 12
	addi r1, 0
	shftli r1, 12
	addi r1, 0
	shftli r1, 12
	addi r1, 0
	shftli r1, 12
	addi r1, 0
	shftli r1, 4
	addi r1, 15
	subi r2, 2
	priv r0, r0, r0, 0
