; Read a sorted array and a target value, then print whether the target exists.
; r1 = item count, r2 = items read, r3 = current item, r10 = memory pointer
; r15 = target value
.code
	clr r10
	ld r10, 65536
	clr r1
	in r1, r0
	clr r2
	ld r5, :startBinaryLoop
	ld r6, :inputLoop
	brgt r5, r2, r1
:inputLoop
	in r3, r0
	mov (r10)(0), r3
	addi r10, 8
	addi r2, 1
	brgt r6, r1, r2
; r18 = middle value, r19 = middle address, r20 = left index
; r21 = right index, r22 = middle index, r23 = byte offset
	ld r30, 65536
	ld r7, :searchLeftHalf
	clr r20
	clr r21
	mov r21, r1
	subi r21, 1
	ld r12, :notFound
	in r15, r0
:startBinaryLoop
	brgt r12, r20, r21
	add r22, r20, r21
	shftri r22, 1
	mov r23, r22
	shftli r23, 3
	add r19, r30, r23
	mov r18, (r19)(0)
	xor r25, r18, r15
	ld r26, :notEqual
	brnz r26, r25
; Print "found".
	clr r27
	addi r27, 3
	clr r28
	addi r28, 102
	out r27, r28
	clr r28
	addi r28, 111
	out r27, r28
	clr r28
	addi r28, 117
	out r27, r28
	clr r28
	addi r28, 110
	out r27, r28
	clr r28
	addi r28, 100
	out r27, r28
	halt
:notEqual
	brgt r7, r18, r15
	mov r20, r22
	addi r20, 1
	br r5
:searchLeftHalf
	mov r21, r22
	subi r21, 1
	br r5
:notFound
; Print "not found".
	clr r27
	addi r27, 3
	clr r28
	addi r28, 110
	out r27, r28
	clr r28
	addi r28, 111
	out r27, r28
	clr r28
	addi r28, 116
	out r27, r28
	clr r28
	addi r28, 32
	out r27, r28
	clr r28
	addi r28, 102
	out r27, r28
	clr r28
	addi r28, 111
	out r27, r28
	clr r28
	addi r28, 117
	out r27, r28
	clr r28
	addi r28, 110
	out r27, r28
	clr r28
	addi r28, 100
	out r27, r28
	halt
